# Generated by Django 3.0.5 on 2020-04-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='toppingsList',
            field=models.CharField(default='', max_length=100),
        ),
    ]
