# Generated by Django 3.0.5 on 2020-04-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_shoppingcart_toppingslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='price',
            field=models.FloatField(),
        ),
    ]
