# Generated by Django 3.0.5 on 2020-04-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200425_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='price',
            field=models.FloatField(blank=True),
        ),
    ]
