# Generated by Django 3.0.5 on 2020-04-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200425_1832'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserOrders',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='approved',
            field=models.CharField(blank=True, default='None', max_length=10, null=True),
        ),
    ]
